CREATE TABLE `config` (
  `down` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT INTO `config` (`down`) VALUES
(0);
ALTER TABLE `config`
  ADD PRIMARY KEY (`down`);

ALTER TABLE `config`
  MODIFY `down` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;
